### ISSUE TITLE
Error when leech google drive folder

### ISSUE THREAD

**Issue by tuthanika** [Sam-Max/rcmltb#146]
2023-05-26 00:54:57,475 - bot.helper.mirror_leech_utils.upload_utils.gdriveTools - INFO - Authorize with token.pickle
2023-05-26 00:54:58,057 - bot.helper.mirror_leech_utils.upload_utils.gdriveTools - INFO - Counting: 1
2023-05-26 00:54:58,463 - bot.helper.mirror_leech_utils.upload_utils.gdriveTools - INFO - Authorize with token.pickle
2023-05-26 00:54:58,633 - pyrogram.dispatcher - ERROR - __init__() takes 5 positional arguments but 6 were given
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/pyrogram/dispatcher.py", line 240, in handler_worker
await handler.callback(self.client, *args)
File "/usr/src/app/bot/modules/leech.py", line 184, in selection_callback
await mirror_leech(client, message, isZip=is_zip, extract=extract, isLeech=True)
File "/usr/src/app/bot/modules/mirror_leech.py", line 196, in mirror_leech
await add_gd_download(link, path, listener, name)
File "/usr/src/app/bot/helper/mirror_leech_utils/download_utils/gd_downloader.py", line 21, in add_gd_download
status_dict[listener.uid] = GdriveStatus(drive, size, listener.message, gid, 'dl')
TypeError: __init__() takes 5 positional arguments but 6 were given

**Comment by Sam-Max** [comment]
> 2023-05-26 00:54:57,475 - bot.helper.mirror_leech_utils.upload_utils.gdriveTools - INFO - Authorize with token.pickle 2023-05-26 00:54:58,057 - bot.helper.mirror_leech_utils.upload_utils.gdriveTools - INFO - Counting: 1 2023-05-26 00:54:58,463 - bot.helper.mirror_leech_utils.upload_utils.gdriveTools - INFO - Authorize with token.pickle 2023-05-26 00:54:58,633 - pyrogram.dispatcher - ERROR - **init**() takes 5 positional arguments but 6 were given Traceback (most recent call last): File "/usr/local/lib/python3.8/dist-packages/pyrogram/dispatcher.py", line 240, in handler_worker await handler.callback(self.client, *args) File "/usr/src/app/bot/modules/leech.py", line 184, in selection_callback await mirror_leech(client, message, isZip=is_zip, extract=extract, isLeech=True) File "/usr/src/app/bot/modules/mirror_leech.py", line 196, in mirror_leech await add_gd_download(link, path, listener, name) File "/usr/src/app/bot/helper/mirror_leech_utils/download_utils/gd_downloader.py", line 21, in add_gd_download status_dict[listener.uid] = GdriveStatus(drive, size, listener.message, gid, 'dl') TypeError: **init**() takes 5 positional arguments but 6 were given

Ok, I will fix soon, forgot to test this

**Comment by Sam-Max** [comment]
Fixed now
