### ISSUE TITLE
Key error while adding new Task

### ISSUE THREAD

**Issue by XTelegram** [Sam-Max/rcmltb#147]
It's giving key error while adding new task [Telegram file To cloud]

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "/usr/src/app/bot/modules/mirror_leech.py", line 277, in mirror_select
    info= listener_dict[message_id]
KeyError: 1226634960

**Comment by Sam-Max** [comment]
> mirror_select

send full logs and more details on telegram channel
