### ISSUE TITLE
Can’t deploy

### ISSUE THREAD

**Issue by ACHIYA96** [Sam-Max/rcmltb#153]
I just cloned the latest master branch and tried to deploy the bot.
But I got the following error. Then it just exits.

```
usr@rcmltb:~$ sudo docker run -p 80:80 -p 8080:8080 rcmltb
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/usr/src/app/bot/__init__.py", line 92, in <module>
    with open(file_, 'wb+') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/src/app/users/grclone/rclone.conf'
```

**Comment by ACHIYA96** [comment]
Solution - Clear database or use a new database
